// BAC streams with subjects + coefficients (Algerian system)
export interface Subject {
  id: string;
  name: string;
  nameFr: string;
  coef: number;
}

export interface Stream {
  id: string;
  name: string;
  emoji: string;
  subjects: Subject[];
}


export const STREAMS: Stream[] = [
  // ==========================
  // SCIENCES EXPÉRIMENTALES
  // ==========================
  {
    id: "sci",
    name: "علوم تجريبية",
    emoji: "🧪",
    subjects: [
     { id: "svt",  name: "علوم الطبيعة والحياة", nameFr: "SVT", coef: 6 },
     { id: "phy",  name: "العلوم الفيزيائية",    nameFr: "Physique", coef: 5 },
     { id: "math", name: "الرياضيات",            nameFr: "Mathématiques", coef: 5 },

     { id: "ar",   name: "اللغة العربية",        nameFr: "Arabe", coef: 3 },
     { id: "fr",   name: "اللغة الفرنسية",      nameFr: "Français", coef: 2 },
     { id: "en",   name: "اللغة الإنجليزية",    nameFr: "Anglais", coef: 2 },

     { id: "hg",   name: "التاريخ والجغرافيا",   nameFr: "Histoire-Géo", coef: 2 },
     { id: "is",   name: "العلوم الإسلامية",     nameFr: "Sciences Islamiques", coef: 2 },
     { id: "ph",   name: "الفلسفة",             nameFr: "Philosophie", coef: 2 },

     { id: "sp",   name: "التربية البدنية",      nameFr: "Sport", coef: 1 },
    ],
  },

  {
    id: 'math',
    name: 'رياضيات',
    emoji: '📐',
    subjects: [
     { id: "math", name: "الرياضيات", nameFr: "Mathématiques", coef: 7 },
     { id: "phy",  name: "العلوم الفيزيائية", nameFr: "Physique", coef: 6 },
     { id: "svt",  name: "علوم الطبيعة والحياة", nameFr: "SVT", coef: 2 },

     { id: "ar",   name: "اللغة العربية", nameFr: "Arabe", coef: 3 },
     { id: "fr",   name: "اللغة الفرنسية", nameFr: "Français", coef: 2 },
     { id: "en",   name: "اللغة الإنجليزية", nameFr: "Anglais", coef: 2 },

     { id: "hg",   name: "التاريخ والجغرافيا", nameFr: "Histoire-Géo", coef: 2 },
     { id: "is",   name: "العلوم الإسلامية", nameFr: "Sciences Islamiques", coef: 2 },
     { id: "ph",   name: "الفلسفة", nameFr: "Philosophie", coef: 2 },

     { id: "sp",   name: "التربية البدنية", nameFr: "Sport", coef: 1 },
   ],
  },
  {
    id: 'tech',
    name: 'تقني رياضي',
    emoji: '⚙️',
   subjects: [
     { id: "tech", name: "التكنولوجيا", nameFr: "Technologie", coef: 7 },
     { id: "math", name: "الرياضيات", nameFr: "Mathématiques", coef: 6 },
     { id: "phy",  name: "العلوم الفيزيائية", nameFr: "Physique", coef: 6 },

     { id: "ar", name: "اللغة العربية", nameFr: "Arabe", coef: 3 },
     { id: "fr", name: "اللغة الفرنسية", nameFr: "Français", coef: 2 },
     { id: "en", name: "اللغة الإنجليزية", nameFr: "Anglais", coef: 2 },

     { id: "hg", name: "التاريخ والجغرافيا", nameFr: "Histoire-Géo", coef: 2 },
     { id: "is", name: "العلوم الإسلامية", nameFr: "Sciences Islamiques", coef: 2 },
     { id: "ph", name: "الفلسفة", nameFr: "Philosophie", coef: 2 },

     { id: "sp", name: "التربية البدنية", nameFr: "Sport", coef: 1 },
    ],
  },
  {
    id: 'gest',
    name: 'تسيير واقتصاد',
    emoji: '📊',
    subjects: [
     { id: "mg",   name: "التسيير المحاسبي والمالي", nameFr: "Comptabilité-Gestion", coef: 6 },
     { id: "eco",  name: "الاقتصاد والمناجمنت", nameFr: "Économie-Gestion", coef: 5 },
     { id: "math", name: "الرياضيات", nameFr: "Mathématiques", coef: 5 },
     { id: "dr",   name: "القانون", nameFr: "Droit", coef: 2 },

     { id: "ar", name: "اللغة العربية", nameFr: "Arabe", coef: 3 },
     { id: "fr", name: "اللغة الفرنسية", nameFr: "Français", coef: 2 },
     { id: "en", name: "اللغة الإنجليزية", nameFr: "Anglais", coef: 2 },

     { id: "hg", name: "التاريخ والجغرافيا", nameFr: "Histoire-Géo", coef: 4 },
     { id: "is", name: "العلوم الإسلامية", nameFr: "Sciences Islamiques", coef: 2 },
     { id: "ph", name: "الفلسفة", nameFr: "Philosophie", coef: 2 },

     { id: "sp", name: "التربية البدنية", nameFr: "Sport", coef: 1 },
    ],
  },
  {
    id: 'lit',
    name: 'آداب وفلسفة',
    emoji: '📖',
   subjects: [
     { id: "ar", name: "اللغة العربية", nameFr: "Arabe", coef: 6 },
     { id: "ph", name: "الفلسفة", nameFr: "Philosophie", coef: 6 },

     { id: "fr", name: "اللغة الفرنسية", nameFr: "Français", coef: 3 },
     { id: "en", name: "اللغة الإنجليزية", nameFr: "Anglais", coef: 3 },

     { id: "math", name: "الرياضيات", nameFr: "Mathématiques", coef: 2 },

     { id: "hg", name: "التاريخ والجغرافيا", nameFr: "Histoire-Géo", coef: 4 },
     { id: "is", name: "العلوم الإسلامية", nameFr: "Sciences Islamiques", coef: 2 },

     { id: "sp", name: "التربية البدنية", nameFr: "Sport", coef: 1 },
    ],
  },
  {
    id: 'lang',
    name: 'لغات أجنبية',
    emoji: '🌍',
    subjects: [
     { id: "fr", name: "اللغة الفرنسية", nameFr: "Français", coef: 5 },
     { id: "en", name: "اللغة الإنجليزية", nameFr: "Anglais", coef: 5 },
     { id: "l3", name: "اللغة الأجنبية الثالثة", nameFr: "Troisième Langue Étrangère", coef: 4 },
     { id: "ar", name: "اللغة العربية", nameFr: "Arabe", coef: 5 },

     { id: "math", name: "الرياضيات", nameFr: "Mathématiques", coef: 2 },

     { id: "hg", name: "التاريخ والجغرافيا", nameFr: "Histoire-Géo", coef: 2 },
     { id: "is", name: "العلوم الإسلامية", nameFr: "Sciences Islamiques", coef: 2 },
     { id: "ph", name: "الفلسفة", nameFr: "Philosophie", coef: 2 },

     { id: "sp", name: "التربية البدنية", nameFr: "Sport", coef: 1 },
    ],
  },
];

export type UniversityStreamKey =
  | 'science'
  | 'math'
  | 'technical_math'
  | 'management'
  | 'literature'
  | 'foreign_languages';

export interface WeightedField {
  subjectId: string;
  weight: number;
}

export interface UniversitySpecialty {
  id: string;
  name: string;
  nameFr: string;
  emoji: string;
  stream: UniversityStreamKey;
  minAverage: number;
  maxAverage: number;
  importantSubjects: string[];
  category: string;
  prestigeLevel: 1 | 2 | 3;
  weightedAverageSubjects?: WeightedField[];
  weightedAverageFormula?: string;
}

export const universityEngine: Record<UniversityStreamKey, UniversitySpecialty[]> = {
  science: [
    {
      id: 'medicine',
      name: 'الطب',
      nameFr: 'Médecine',
      emoji: '🩺',
      stream: 'science',
      minAverage: 16,
      maxAverage: 18.5,
      importantSubjects: ['svt', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [{ subjectId: 'svt', weight: 2 }],
      weightedAverageFormula: '(avg + 2×SVT) / 3',
    },
    {
      id: 'dentistry',
      name: 'طب الأسنان',
      nameFr: 'Chirurgie Dentaire',
      emoji: '🦷',
      stream: 'science',
      minAverage: 15.5,
      maxAverage: 18,
      importantSubjects: ['svt', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [{ subjectId: 'svt', weight: 2 }],
      weightedAverageFormula: '(avg + 2×SVT) / 3',
    },
    {
      id: 'pharmacy',
      name: 'الصيدلة',
      nameFr: 'Pharmacie',
      emoji: '💊',
      stream: 'science',
      minAverage: 15.5,
      maxAverage: 17.5,
      importantSubjects: ['svt', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [{ subjectId: 'svt', weight: 2 }],
      weightedAverageFormula: '(avg + 2×SVT) / 3',
    },
    {
      id: 'ai_school',
      name: 'مدرسة الذكاء الاصطناعي',
      nameFr: 'AI School',
      emoji: '🤖',
      stream: 'science',
      minAverage: 15,
      maxAverage: 17.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'computer_science',
      name: 'إعلام آلي',
      nameFr: 'Computer Science',
      emoji: '💻',
      stream: 'science',
      minAverage: 14,
      maxAverage: 17,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'paramedical',
      name: 'شبه طبي',
      nameFr: 'Paramédical',
      emoji: '🧑‍⚕️',
      stream: 'science',
      minAverage: 13,
      maxAverage: 15.5,
      importantSubjects: ['svt'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'biology',
      name: 'البيولوجيا',
      nameFr: 'Biologie',
      emoji: '🧬',
      stream: 'science',
      minAverage: 12,
      maxAverage: 14.5,
      importantSubjects: ['svt'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'biotechnology',
      name: 'التكنولوجيا الحيوية',
      nameFr: 'Biotechnologie',
      emoji: '🧫',
      stream: 'science',
      minAverage: 12,
      maxAverage: 15,
      importantSubjects: ['svt', 'phy'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'food_science',
      name: 'علوم الأغذية',
      nameFr: 'Food Science',
      emoji: '🍏',
      stream: 'science',
      minAverage: 11.5,
      maxAverage: 14,
      importantSubjects: ['svt'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'natural_sciences',
      name: 'العلوم الطبيعية',
      nameFr: 'Natural Sciences',
      emoji: '🌿',
      stream: 'science',
      minAverage: 10.5,
      maxAverage: 13.5,
      importantSubjects: ['svt'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
    {
      id: 'environmental_sciences',
      name: 'علوم البيئة',
      nameFr: 'Environmental Sciences',
      emoji: '🌍',
      stream: 'science',
      minAverage: 10.5,
      maxAverage: 13.5,
      importantSubjects: ['svt'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
  ],
  math: [
    {
      id: 'ensia',
      name: 'ENSIA',
      nameFr: 'ENSIA',
      emoji: '🏛️',
      stream: 'math',
      minAverage: 16.5,
      maxAverage: 18.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'computer_science_math',
      name: 'إعلام آلي',
      nameFr: 'Computer Science',
      emoji: '💻',
      stream: 'math',
      minAverage: 15,
      maxAverage: 17.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'ai_school_math',
      name: 'مدرسة الذكاء الاصطناعي',
      nameFr: 'AI School',
      emoji: '🤖',
      stream: 'math',
      minAverage: 15,
      maxAverage: 17.5,
      importantSubjects: ['math'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'polytech_math',
      name: 'Polytech',
      nameFr: 'Polytech',
      emoji: '🛰️',
      stream: 'math',
      minAverage: 16.5,
      maxAverage: 18.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'phy', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Physique) / 4',
    },
    {
      id: 'telecom',
      name: 'اتصالات',
      nameFr: 'Telecom',
      emoji: '📡',
      stream: 'math',
      minAverage: 15,
      maxAverage: 17.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'phy', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Physique) / 4',
    },
    {
      id: 'mathematics',
      name: 'الرياضيات',
      nameFr: 'Mathematics',
      emoji: '➗',
      stream: 'math',
      minAverage: 13.5,
      maxAverage: 16,
      importantSubjects: ['math'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'electronics',
      name: 'الإلكترونيات',
      nameFr: 'Electronics',
      emoji: '🔌',
      stream: 'math',
      minAverage: 13,
      maxAverage: 15.5,
      importantSubjects: ['math', 'phy'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'automation',
      name: 'الأتمتة',
      nameFr: 'Automation',
      emoji: '⚙️',
      stream: 'math',
      minAverage: 13,
      maxAverage: 15.5,
      importantSubjects: ['math', 'phy'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'physics_math',
      name: 'الفيزياء التطبيقية',
      nameFr: 'Applied Physics',
      emoji: '🔭',
      stream: 'math',
      minAverage: 12,
      maxAverage: 14.5,
      importantSubjects: ['phy', 'math'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
    {
      id: 'applied_mathematics',
      name: 'الرياضيات التطبيقية',
      nameFr: 'Applied Mathematics',
      emoji: '📐',
      stream: 'math',
      minAverage: 12,
      maxAverage: 14.5,
      importantSubjects: ['math'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
  ],
  technical_math: [
    {
      id: 'engineering',
      name: 'الهندسة',
      nameFr: 'Engineering',
      emoji: '🛠️',
      stream: 'technical_math',
      minAverage: 15.5,
      maxAverage: 18.5,
      importantSubjects: ['math', 'tech', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'phy', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Physique) / 4',
    },
    {
      id: 'polytech_tech',
      name: 'Polytech',
      nameFr: 'Polytech',
      emoji: '🛰️',
      stream: 'technical_math',
      minAverage: 15.5,
      maxAverage: 18,
      importantSubjects: ['math', 'tech'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'tech', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Tech) / 4',
    },
    {
      id: 'mechanical_engineering',
      name: 'الهندسة الميكانيكية',
      nameFr: 'Mechanical Engineering',
      emoji: '⚙️',
      stream: 'technical_math',
      minAverage: 14,
      maxAverage: 16.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'phy', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Physique) / 4',
    },
    {
      id: 'electrical_engineering',
      name: 'الهندسة الكهربائية',
      nameFr: 'Electrical Engineering',
      emoji: '🔌',
      stream: 'technical_math',
      minAverage: 14,
      maxAverage: 16.5,
      importantSubjects: ['math', 'phy'],
      category: 'High-demand',
      prestigeLevel: 3,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'phy', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Physique) / 4',
    },
    {
      id: 'civil_engineering',
      name: 'الهندسة المدنية',
      nameFr: 'Civil Engineering',
      emoji: '🏗️',
      stream: 'technical_math',
      minAverage: 13,
      maxAverage: 15.5,
      importantSubjects: ['math', 'tech'],
      category: 'Medium-demand',
      prestigeLevel: 2,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'tech', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Tech) / 4',
    },
    {
      id: 'automation_tech',
      name: 'الأتمتة',
      nameFr: 'Automation',
      emoji: '🤖',
      stream: 'technical_math',
      minAverage: 13,
      maxAverage: 15.5,
      importantSubjects: ['math', 'tech'],
      category: 'Medium-demand',
      prestigeLevel: 2,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'tech', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Tech) / 4',
    },
    {
      id: 'industrial_engineering',
      name: 'الهندسة الصناعية',
      nameFr: 'Industrial Engineering',
      emoji: '🏭',
      stream: 'technical_math',
      minAverage: 13,
      maxAverage: 15.5,
      importantSubjects: ['math', 'tech'],
      category: 'Medium-demand',
      prestigeLevel: 2,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'tech', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Tech) / 4',
    },
    {
      id: 'energy_engineering',
      name: 'هندسة الطاقة',
      nameFr: 'Energy Engineering',
      emoji: '⚡',
      stream: 'technical_math',
      minAverage: 12,
      maxAverage: 14.5,
      importantSubjects: ['math', 'phy'],
      category: 'Low-demand',
      prestigeLevel: 1,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'phy', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Physique) / 4',
    },
    {
      id: 'maintenance',
      name: 'الصيانة',
      nameFr: 'Maintenance',
      emoji: '🛡️',
      stream: 'technical_math',
      minAverage: 11.5,
      maxAverage: 14,
      importantSubjects: ['math', 'tech'],
      category: 'Low-demand',
      prestigeLevel: 1,
      weightedAverageSubjects: [
        { subjectId: 'math', weight: 2 },
        { subjectId: 'tech', weight: 1 },
      ],
      weightedAverageFormula: '(avg + 2×Math + Tech) / 4',
    },
  ],
  management: [
    {
      id: 'commerce_school',
      name: 'مدرسة التجارة',
      nameFr: 'Commerce School',
      emoji: '🏛️',
      stream: 'management',
      minAverage: 15,
      maxAverage: 18,
      importantSubjects: ['eco', 'mg'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'finance',
      name: 'المالية',
      nameFr: 'Finance',
      emoji: '💰',
      stream: 'management',
      minAverage: 14,
      maxAverage: 17,
      importantSubjects: ['eco', 'math'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'accounting',
      name: 'المحاسبة',
      nameFr: 'Accounting',
      emoji: '🧾',
      stream: 'management',
      minAverage: 14,
      maxAverage: 17,
      importantSubjects: ['mg', 'math'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'management_major',
      name: 'تسيير',
      nameFr: 'Management',
      emoji: '📊',
      stream: 'management',
      minAverage: 14,
      maxAverage: 17,
      importantSubjects: ['mg', 'eco'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'economics',
      name: 'الاقتصاد',
      nameFr: 'Economics',
      emoji: '📈',
      stream: 'management',
      minAverage: 12.5,
      maxAverage: 15.5,
      importantSubjects: ['eco', 'mg'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'marketing',
      name: 'التسويق',
      nameFr: 'Marketing',
      emoji: '📣',
      stream: 'management',
      minAverage: 12.5,
      maxAverage: 15.5,
      importantSubjects: ['eco', 'mg'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'business_administration',
      name: 'إدارة الأعمال',
      nameFr: 'Business Administration',
      emoji: '💼',
      stream: 'management',
      minAverage: 12,
      maxAverage: 15,
      importantSubjects: ['mg', 'eco'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'commercial_sciences',
      name: 'العلوم التجارية',
      nameFr: 'Commercial Sciences',
      emoji: '🛒',
      stream: 'management',
      minAverage: 11,
      maxAverage: 13.5,
      importantSubjects: ['eco', 'mg'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
  ],
  literature: [
    {
      id: 'law_lit',
      name: 'الحقوق',
      nameFr: 'Law',
      emoji: '⚖️',
      stream: 'literature',
      minAverage: 13,
      maxAverage: 16,
      importantSubjects: ['ar', 'hg'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'psychology_lit',
      name: 'علم النفس',
      nameFr: 'Psychology',
      emoji: '🧠',
      stream: 'literature',
      minAverage: 12.5,
      maxAverage: 15,
      importantSubjects: ['phLit', 'arLit'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'translation_lit',
      name: 'الترجمة',
      nameFr: 'Translation',
      emoji: '🌐',
      stream: 'literature',
      minAverage: 12,
      maxAverage: 15.5,
      importantSubjects: ['arLit', 'fr', 'en'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'arabic_literature',
      name: 'الأدب العربي',
      nameFr: 'Arabic Literature',
      emoji: '📚',
      stream: 'literature',
      minAverage: 11.5,
      maxAverage: 14.5,
      importantSubjects: ['arLit', 'phLit'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'islamic_sciences',
      name: 'العلوم الإسلامية',
      nameFr: 'Islamic Sciences',
      emoji: '🕌',
      stream: 'literature',
      minAverage: 11,
      maxAverage: 14,
      importantSubjects: ['is', 'arLit'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'history',
      name: 'التاريخ',
      nameFr: 'History',
      emoji: '🏺',
      stream: 'literature',
      minAverage: 10.5,
      maxAverage: 13.5,
      importantSubjects: ['hg', 'arLit'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
    {
      id: 'philosophy',
      name: 'الفلسفة',
      nameFr: 'Philosophy',
      emoji: '🧭',
      stream: 'literature',
      minAverage: 10.5,
      maxAverage: 13.5,
      importantSubjects: ['phLit', 'arLit'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
  ],
  foreign_languages: [
    {
      id: 'translation_lang',
      name: 'الترجمة',
      nameFr: 'Translation',
      emoji: '🌐',
      stream: 'foreign_languages',
      minAverage: 12,
      maxAverage: 15.5,
      importantSubjects: ['fr', 'en'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'english_studies',
      name: 'الدراسات الإنجليزية',
      nameFr: 'English Studies',
      emoji: '🇬🇧',
      stream: 'foreign_languages',
      minAverage: 11.5,
      maxAverage: 15,
      importantSubjects: ['en', 'fr'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'international_relations',
      name: 'العلاقات الدولية',
      nameFr: 'International Relations',
      emoji: '🌍',
      stream: 'foreign_languages',
      minAverage: 11.5,
      maxAverage: 15,
      importantSubjects: ['en', 'hg'],
      category: 'High-demand',
      prestigeLevel: 3,
    },
    {
      id: 'french_studies',
      name: 'الدراسات الفرنسية',
      nameFr: 'French Studies',
      emoji: '🇫🇷',
      stream: 'foreign_languages',
      minAverage: 11,
      maxAverage: 14,
      importantSubjects: ['fr', 'en'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'spanish_studies',
      name: 'الدراسات الإسبانية',
      nameFr: 'Spanish Studies',
      emoji: '🇪🇸',
      stream: 'foreign_languages',
      minAverage: 11,
      maxAverage: 14,
      importantSubjects: ['fr', 'en'],
      category: 'Medium-demand',
      prestigeLevel: 2,
    },
    {
      id: 'literature_lang',
      name: 'الآداب',
      nameFr: 'Literature',
      emoji: '📖',
      stream: 'foreign_languages',
      minAverage: 10.5,
      maxAverage: 13.5,
      importantSubjects: ['arLit', 'fr', 'en'],
      category: 'Low-demand',
      prestigeLevel: 1,
    },
  ],
};
